# Setup
title:        xMsg
tagline:      Multilingual publish-subscribe messaging system
baseurl:      /xmsg

# About/contact
author:
  name:       Vardan Gyurjyan
  url:        https://claraweb.jlab.org

# Main Docs
exclude:
  - build
  - source
  - Makefile
  - README.md
  - scripts
  - Dockerfile
  - docker-compose.yml

defaults:
  - scope:
      path: docs
    values:
      layout: document

# Others
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
